### ISSUE TITLE
The Listener Only Work if i manually change data on SSMS!

### ISSUE THREAD

**Issue by imangh26** [dyatchenko/ServiceBrokerListener#32]
The Listener Only Work if i manually change data on SSMS! 
If data changes by sp or by update command of ado.net dataset nothing happen at all.

**Comment by dyatchenko** [comment]
Hi @imangh26,

There are unit tests in the project which test this case. Were you able to run them?

Thanks,
Dmitrii

**Comment by imangh26** [comment]
Hi @dyatchenko 
Yes,Unit Test of your project run successfully.
I referenced DLL of sqldependencyex on my vb.net example project.
some of text codes ::
`Friend WithEvents InsertListener As SqlDependencyEx`

`InsertListener = New SqlDependencyEx(Me.taAnbari_ElamBar.Connection.ConnectionString, "Gostaresh", "Anbari_ElamBar", "dbo", SqlDependencyEx.NotificationTypes.Insert, True, 1)`
`InsertListener.Start()`
```
Private Sub InsertListener_TableChanged(sender As Object, e As 
SqlDependencyEx.TableChangedEventArgs) Handles InsertListener.TableChanged
        MsgBox("New Record Inserted!")
        MsgBox(e.NotificationType.ToString)
End Sub
```

when i make change on data from SSMS the event raises but if i run another instance of my project thats able to update or insert some datas , the upper event not firing at all.
thanks alot

**Comment by dyatchenko** [comment]
You probably start two listeners with the same identities. And the second listener drops settings for the first one. This situation is described in HOW TO section:

How to use for multiple tables

All you need to do is to create multiple listeners with different identities as shown below:

var listener1 = new SqlDependencyEx(connectionString, "YourDatabase", "YourTable1", identity: 1);
var listener2 = new SqlDependencyEx(connectionString, "YourDatabase", "YourTable2", identity: 2);

Hm, I see now that it is unclear from this example that only one instance of the listener should exist at the moment (with a specific Id). E.g. if you want to listen to even the same table from two different apps you should create listeners in each app with **different** identities. It was tried to overcome this problem, but this logic was the best one in order to make sure that the resources are cleaned up.

Thanks,
Dmitrii

**Comment by imangh26** [comment]
Yes , I had 2 Listeners,I write both for one datatable with two identies after remove one of them i want to write one listner and control Insert or Update on Event Handler by e.NotificationType.
thanks alot @dyatchenko

**Comment by dyatchenko** [comment]
[ReadMe](https://github.com/dyatchenko/ServiceBrokerListener/blob/master/README.md) has been updated. Take a look at it please.

Ok, great. So your issue is solved now?

Thanks,
Dmitrii

**Comment by imangh26** [comment]
Yes. my issue solved now. thanks alot

**Comment by dyatchenko** [comment]
You are welcome @imangh26 !
