### ISSUE TITLE
ListenerServices and ListenerQueues

### ISSUE THREAD

**Issue by Chesheersky** [dyatchenko/ServiceBrokerListener#4]
After a couple of days experimenting with ServiceBrokerListener I have found out that I have about 100-200 ListenerServices and ListenerQueues in my DB.
I'll try to find a solution a bit later, right now I am too busy cleaning the db. Deleting a service takes a lot of time. =)

**Comment by dyatchenko** [comment]
Make sure you give opportunity for a component to cleanup after itself. It deletes all notification stuff from the database inside Dispose method. I wrote couple of tests to check it (ResourcesReleasabilityTestWith10Changes()). Anyway, in this case you don't need to remove all services and queues manually - there is special stored procedure to do it (sp_UninstallListenerNotification_{0}). 
To clean up database in case of app crash I used to use a little bit modified notification trigger in my project - it checked number of messages in notification queue and if this amount is greater than specific number (it means nobody receive notification and probably app is crashed) It will remove all notification stuff from the database including itself. But for this open source component I decided to use last message timestamps instead of amount of messages in a notification queue, and I haven't committed yet. I will do it in a couple of days. 
Thus, while I don't finish with auto-cleanup in case of app crash - here is script which cleans all old notification for you:

USE [TestDatabase]

DECLARE @db_name VARCHAR(MAX) 
DECLARE @schema_name VARCHAR(MAX)
SET @db_name = 'TestDatabase'     -- provide your own db name
SET @schema_name = 'Temp'	  -- provide your schema name

DECLARE @proc_name VARCHAR(MAX)
DECLARE procedures CURSOR 
FOR
	SELECT [name]
	FROM sys.objects 
	WHERE [type] = 'P' AND [name] like 'sp_UninstallListenerNotification_%'

OPEN procedures;
FETCH NEXT FROM procedures INTO @proc_name 

WHILE (@@FETCH_STATUS = 0)
BEGIN
	EXEC ('USE [' + @db_name + '] EXEC ' + @schema_name 
				+ '.' + @proc_name + ' DROP PROCEDURE ' 
				+ @schema_name + '.' +@proc_name)	
	FETCH NEXT FROM procedures INTO @proc_name 
END

CLOSE procedures;
DEALLOCATE procedures;

DECLARE procedures CURSOR 
FOR
	SELECT [name]
	FROM sys.objects 
	WHERE [type] = 'P' AND [name] like 'sp_InstallListenerNotification_%'

OPEN procedures;
FETCH NEXT FROM procedures INTO @proc_name 

WHILE (@@FETCH_STATUS = 0)
BEGIN
	EXEC ('USE [' + @db_name + '] DROP PROCEDURE ' 
				+ @schema_name + '.' +@proc_name)	
	FETCH NEXT FROM procedures INTO @proc_name 
END

CLOSE procedures;
DEALLOCATE procedures;

**Comment by dyatchenko** [comment]
New and fixed version has SqlDependencyEx that is created with special int identifier (1 default), and there is no way to start two of this components with the same identity. Each database object has strict relation with identity number and every time when you create a new instance it will use same db components. Event though your app is crashed (it means database objects won't be deleted from the database and continue work without memory leaks of course - each conversation point has 1 minute lifetime) database components will be deleted in case of next successful disposing.
Also, new SqlDependencyEx has static method ClearDatabase() which makes forced database cleaning. You can use it if you want to be sure about disposing of all trash components from the database.
