### ISSUE TITLE
SqlDependencyEx event inside Controller not getting fired

### ISSUE THREAD

**Issue by VanilsonWDD** [dyatchenko/ServiceBrokerListener#47]
Hi Devs,
I´m trying to use SqlDependencyEx the problem is that the OnDataChange event is not getting fired inside the controller, I already enabled Service Broker. Here´s is the code:

`

    private const string CONNECTION_STRING  = "Server=LFTCMCPTP83;Database=Database;Trusted_Connection=True;MultipleActiveResultSets=true;  Integrated Security=false;User ID=used_id;Password=password";
    private const string DATABASE_NAME = "db_name";

    private const string TABLE_NAME = "table_name";

    private const string SCHEMA_NAME = "dbo";

    private SqlDependencyEx sqlDependency = new SqlDependencyEx(CONNECTION_STRING, DATABASE_NAME,
        TABLE_NAME, SCHEMA_NAME);

    private void RegisterNotification()
    {
        sqlDependency.TableChanged += OnDataChange;
        sqlDependency.Start();
    }

    private void OnDataChange(object sender, SqlDependencyEx.TableChangedEventArgs e)
    {
        //Code
    }

    public IActionResult Create(){
         RegisterNotification();
    }`

Best Regards

**Comment by Siliconrob** [comment]
Are you publishing events inside web MVC or WebApi?  I ask because you have the IActionResult as the type which I mean is a problem if you are.  If you are long running threads on a webserver should be using websockets to persist or server sent events or some other technology that either keeps the connection open to continue listening or sends push notifications out of the server.

You could also use [weak events](https://github.com/thomaslevesque/WeakEvent) if you really want to use events I presume.  I haven't messed with this in a web environment, but it should work as the references don't need to persist to send them

**Comment by VanilsonWDD** [comment]
Problem solved, here´s the code:


` private const string CONNECTION_STRING = "Server=LFTCMCPTP83;Database=Database;Trusted_Connection=True;MultipleActiveResultSets=true; Integrated Security=false;User ID=used_id;Password=password";
private const string DATABASE_NAME = "db_name";
private const string TABLE_NAME = "table_name";
private const string SCHEMA_NAME = "dbo";
private SqlDependencyEx sqlDependency = new SqlDependencyEx(CONNECTION_STRING, DATABASE_NAME,
TABLE_NAME, SCHEMA_NAME);
listener.TableChanged += (o, args) =>
{
   //Code...
};
listener.Start();
listener.Stop(); `

Best Regards
