### ISSUE TITLE
How to use in ASP.NET MVC

### ISSUE THREAD

**Issue by ofuochi** [dyatchenko/ServiceBrokerListener#52]
Hello, your library is quit useful but I want to try to integrate it to an existing asp.net mvc application. 
I want to call the **start** and **stop** methods in my **Global.aspx** file in the **Application_Start()** and **Application_End()** respectively. However, the anonymous function `listener.TableChanged += (o, e) => Console.WriteLine("Your table was changed!")` to be in another class which is not in the **Global.aspx** file.

Please can you elaborate with code snippets on how to do this? Additionally, can you direct me to a more elaborate documentation of your library?

Thank you.

**Comment by Siliconrob** [comment]
@ofuochi did you check [47](https://github.com/dyatchenko/ServiceBrokerListener/issues/47)?

**Comment by ofuochi** [comment]
@Siliconrob Thank you for the reference but I'm trying to use it in a asp.net web api with SignalR. All I'm asking is how to **start** and **stop** in the `Global.aspx` file

**Comment by Siliconrob** [comment]
Problem is that the `Global.asax` is not going to keep your reference for the events to populate.  I mean you could make the listener `static`, but that will cause a huge memory leak over time as your users and sessions with stack up in the `Garbage Collecter` of .NET. 

Since you say you are using `SignalR` you can use [Hub](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server#connectionlifetime) class to instantiate the object or maybe try this project [HangFire](https://www.hangfire.io/)

I wish I could add more to this project, but only @dyatchenko has commit privileges on the master, so if you want to make some serious modifications to get this working through ASP.NET I would suggest forking this project and then having me or someone else make the changes you would like `Documentation`

**Comment by ofuochi** [comment]
Thank you @Siliconrob
