### ISSUE TITLE
Error on Service Stopping

### ISSUE THREAD

**Issue by sp00n5** [dyatchenko/ServiceBrokerListener#9]
Hi Dmitriy,
Firstly, nice work, this could help us out a lot!
We are just running it in a console application to do some testing and so far seems to work really well however on stopping we get an unhandled exception during cleanup.  What looks to be happening is that the listener thread is attempting to access the Queue from the ReceiveEvent method after the Queue has already been deleted by the main thread and obviuosly before the listener thread is aborted.
So Error occurs while the object is disposing on line:
 using (var reader = command.ExecuteReader())  

when passing the command:
 DECLARE @ConvHandle UNIQUEIDENTIFIER
                DECLARE @message VARBINARY(MAX)
                USE [Assetic_Local]
                WAITFOR (RECEIVE TOP(1) @ConvHandle=Conversation_Handle
                            , @message=message_body FROM dbo.[ListenerQueue_1]), TIMEOUT 30000;
	            BEGIN TRY END CONVERSATION @ConvHandle; END TRY BEGIN CATCH END CATCH
                SELECT CAST(@message AS NVARCHAR(MAX))

We can work around it, just wanted to see if you had come across it or had any insight on it?

Also, just as a side question, not an issue, just wondering the reason behind the 30sec timeout in the above procedure?  It removes and starts a new conversation every 30secs?

Thanks!

**Comment by dyatchenko** [comment]
Hi,

Thank you for the issue. 
1. The exception happens in a background thread when you stop the listener (i.e. delete notification queue) while the sql is waiting for a notification here: `WAITFOR (RECEIVE TOP(1) ... TIMEOUT 30000;`. It could be handled in the code by adding an extra `catch`, but is it necessary for the background thread which had to be stopped? I think we can prevent this exception by waiting for the next notification or for 30sec (which is not good I guess), so I decided to leave it as it was.
2. The reason for 30 sec is here:

     string message = ReceiveEvent();
     this.Active = true;   // We can see that the listener works even though we don't have notifications
     if (!string.IsNullOrWhiteSpace(message))
            OnTableChanged(message);

It is like a "Pulse" for the listener. We can see that it works even there aren't any notifications.
The important thing about it is that we don't miss any notification while the last `WAITFOR` instruction ended and the new one is not started yet. It happens because we use the same notification queue and `WAITFOR` just receives the eldest notification from it. A notification queue will receive notifications even there is nobody who receives them.

If you have any questions or problems, please feel free to ask or create an issue - I will answer as soon as possible.

Thanks for the contribution!

**Comment by sp00n5** [comment]
Yea, that makes sense, we put it in a windows service and it exits fine with no error so its only in a console application that it errors and that is not how we will be running it so leaving it as is is fine.
Thanks.
